# Generated by Django 3.2 on 2023-08-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipetag_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='with_ingredients', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
